"""empty message

Revision ID: 6918588eda22
Revises: 
Create Date: 2024-09-11 13:31:43.228463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6918588eda22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_result', sa.Integer(), nullable=False),
    sa.Column('id_nilai', sa.Integer(), nullable=False),
    sa.Column('row', sa.Text(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('kode', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('testsize', sa.Float(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mutasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=False),
    sa.Column('id_mapel', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('nilai', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_model', sa.Integer(), nullable=False),
    sa.Column('id_nilai', sa.Integer(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('testindex', sa.Text(), nullable=True),
    sa.Column('trainindex', sa.Text(), nullable=True),
    sa.Column('y_true', sa.Text(), nullable=True),
    sa.Column('y_pred', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('kode', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('siswa')
    op.drop_table('results')
    op.drop_table('mutasi')
    op.drop_table('models')
    op.drop_table('mapel')
    op.drop_table('data')
    op.drop_table('auth_group')
    # ### end Alembic commands ###
